// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace VleisurePartner.EF.Generator
{

    // Region
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Region
    {
        public int RegionId { get; set; } // RegionID (Primary key)
        public string RegionType { get; set; } // RegionType
        public string RelativeSignificance { get; set; } // RelativeSignificance
        public string SubClass { get; set; } // SubClass
        public string RegionName { get; set; } // RegionName
        public string RegionNameLong { get; set; } // RegionNameLong
        public string ParentRegionType { get; set; } // ParentRegionType
        public string ParentRegionName { get; set; } // ParentRegionName
        public string ParentRegionNameLong { get; set; } // ParentRegionNameLong
        public string CountryName { get; set; } // CountryName
        public string CountryCode { get; set; } // CountryCode
    }

}
// </auto-generated>
